CREATE TABLE tasks (
    id INT IDENTITY(1,1) PRIMARY KEY,
    content NVARCHAR(255) NOT NULL
);

SELECT * FROM tasks

CREATE TABLE Users (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(100),
    Password NVARCHAR(100)
);

ALTER TABLE Users 
ADD Email VARCHAR(50)

ALTER TABLE Users
ADD AccCreatedDate DATETIME DEFAULT GETDATE()

SELECT * FROM Users

ALTER TABLE Users
ADD ConfirmPassword VARCHAR(50)
